version: '3'
services:
  log_emitter:
    build:
      context: .
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./:/usr/src/app
    command: python /usr/src/app/code/log_emmiter.py
    environment:
      IN_DOCKER: yep

  # connect the log_emitter container's /tmp/namedPipes dir
  # into log_collector container's /tmp/cooler dir
  log_collector:
    build:
      context: .
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./:/usr/src/app
    command: python /usr/src/app/code/log_collector.py
    links:
      - timescale_db:timescale_db
    environment:
      IN_DOCKER: yep

  timescale_db:
    build: 
      context: .
      dockerfile: timescale_dockerfile
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: hey_NSA
    ports:
      - 5432:5432
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./:/usr/src/app
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    links:
      - timescale_db:timescale_db

volumes:
  named-pipe-volume:

